# Generated by Django 5.1.6 on 2025-02-08 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0002_vendorcoupon_vendorservicecategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCoupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coupon_name', models.CharField(max_length=10000)),
                ('coupon_price', models.IntegerField()),
                ('coupon_points_hold', models.IntegerField()),
                ('active', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'verbose_name': 'Vendor Coupons',
                'ordering': ['coupon_name'],
            },
        ),
    ]
