# Generated by Django 5.1.6 on 2025-02-08 14:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0003_vendorservicecategory_remove_vendorinvoice_month_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_category', models.CharField(db_index=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Vendor Service Category',
                'ordering': ['service_category'],
            },
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='month',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='week',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='year',
        ),
        migrations.AddField(
            model_name='vendorcoupon',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorcoupon',
            name='vendor_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch'),
        ),
        migrations.AddField(
            model_name='vendorcustomerloyalitypoints',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='vendorcustomers',
            name='d_o_a',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vendorcustomers',
            name='d_o_b',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='json_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='new_mode',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendorloyalityprogramtypes',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='vendorloyalityprogramtypes',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorloyalityprogramtypes',
            name='limit',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorservice',
            name='for_men',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorservice',
            name='for_women',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='swalookuserprofile',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='swalookuserprofile',
            name='mobile_no',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='vendorcustomers',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='vendorcustomers',
            name='membership',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcustomers',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcustomers',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vendorexpense',
            name='expense_category',
            field=models.ManyToManyField(blank=True, to='_api_.vendorexpensecategory'),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='mode_of_payment',
            field=models.CharField(blank=True, default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='service_by',
            field=models.CharField(blank=True, max_length=40000),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='services',
            field=models.CharField(blank=True, max_length=50000),
        ),
        migrations.AlterField(
            model_name='vendorloyalityprogramtypes',
            name='points_hold',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendorservice',
            name='service',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='vendorservice',
            name='service_duration',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='businessanalysis',
            index=models.Index(fields=['user', 'month'], name='Dapi__busin_user_id_1bd605_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdesk',
            index=models.Index(fields=['user', 'email'], name='Dapi__helpd_user_id_ce7c70_idx'),
        ),
        migrations.AddIndex(
            model_name='salonbranch',
            index=models.Index(fields=['vendor_name', 'branch_name'], name='Dapi__salon_vendor__aa7059_idx'),
        ),
        migrations.AddIndex(
            model_name='staffsalary',
            index=models.Index(fields=['vendor_name', 'vendor_branch', 'of_month'], name='Dapi__staff_vendor__b0faa2_idx'),
        ),
        migrations.AddIndex(
            model_name='staffsetting',
            index=models.Index(fields=['vendor_name', 'vendor_branch', 'month'], name='Dapi__staff_vendor__b35694_idx'),
        ),
        migrations.AddIndex(
            model_name='staffsettingslab',
            index=models.Index(fields=['vendor_name', 'vendor_branch'], name='Dapi__staff_vendor__8fae44_idx'),
        ),
        migrations.AddIndex(
            model_name='swalookuserprofile',
            index=models.Index(fields=['salon_name', 'mobile_no'], name='Dapi__swalo_salon_n_3a79dc_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorappointment',
            index=models.Index(fields=['vendor_name', 'vendor_branch', 'booking_date'], name='Dapi__vendo_vendor__39965b_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcoupon',
            index=models.Index(fields=['user', 'vendor_branch', 'coupon_name'], name='Dapi__vendo_user_id_2e3ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcustomerloyalityledger',
            index=models.Index(fields=['user', 'vendor_branch', 'date'], name='Dapi__vendo_user_id_f6ddc8_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcustomerloyalitypoints',
            index=models.Index(fields=['user', 'vendor_branch', 'customer_id'], name='Dapi__vendo_user_id_7e6451_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcustomers',
            index=models.Index(fields=['user', 'vendor_branch', 'mobile_no'], name='Dapi__vendo_user_id_926f17_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorexpense',
            index=models.Index(fields=['user', 'vendor_branch', 'date'], name='Dapi__vendo_user_id_173d71_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorexpensecategory',
            index=models.Index(fields=['user', 'vendor_branch', 'vendor_expense_type'], name='Dapi__vendo_user_id_bde4fb_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorinventoryinvoice',
            index=models.Index(fields=['user', 'vendor_branch', 'date'], name='Dapi__vendo_user_id_d32762_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorinventoryproduct',
            index=models.Index(fields=['user', 'vendor_branch', 'product_name'], name='Dapi__vendo_user_id_41a992_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorinvoice',
            index=models.Index(fields=['vendor_name', 'vendor_branch', 'date'], name='Dapi__vendo_vendor__2c6c77_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorloyalityprogramtypes',
            index=models.Index(fields=['user', 'vendor_branch', 'program_type'], name='Dapi__vendo_user_id_a76282_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpdf',
            index=models.Index(fields=['vendor_branch', 'date'], name='Dapi__vendo_vendor__c13062_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorstaff',
            index=models.Index(fields=['vendor_name', 'vendor_branch', 'staff_name'], name='Dapi__vendo_vendor__2aafca_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorstaffattendance',
            index=models.Index(fields=['vendor_name', 'vendor_branch', 'date'], name='Dapi__vendo_vendor__08433d_idx'),
        ),
        migrations.AddField(
            model_name='vendorservicecategory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorservicecategory',
            name='vendor_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch'),
        ),
        migrations.AddField(
            model_name='vendorservice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.vendorservicecategory'),
        ),
        migrations.AddIndex(
            model_name='vendorservicecategory',
            index=models.Index(fields=['user', 'vendor_branch', 'service_category'], name='Dapi__vendo_user_id_c7e482_idx'),
        ),
    ]
