# Generated by Django 5.1.6 on 2025-02-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0004_vendorservicecategory_remove_vendorinvoice_month_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorCoupon',
        ),
    ]
