# Generated by Django 5.1.6 on 2025-02-08 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0005_delete_vendorcoupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCoupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coupon_name', models.CharField(max_length=160)),
                ('coupon_price', models.IntegerField()),
                ('coupon_points_hold', models.IntegerField()),
                ('active', models.BooleanField(blank=True, default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch')),
            ],
            options={
                'verbose_name': 'Vendor Coupons',
                'ordering': ['coupon_name'],
                'indexes': [models.Index(fields=['user', 'vendor_branch', 'coupon_name'], name='Dapi__vendo_user_id_2e3ba6_idx')],
            },
        ),
    ]
