# Generated by Django 5.1.6 on 2025-02-08 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0006_vendorcoupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCoupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=10000)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('coupon_points_hold', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('coupon_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.vendorcoupon')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch')),
            ],
            options={
                'verbose_name': 'Vendor Coupons',
                'ordering': ['coupon_name'],
                'indexes': [models.Index(fields=['user', 'vendor_branch', 'coupon_name'], name='Dapi__custo_user_id_86bf0b_idx')],
            },
        ),
    ]
