# Generated by Django 5.1.6 on 2025-02-08 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0007_customercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcustomers',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.customercoupon'),
        ),
    ]
