# Generated by Django 5.1.6 on 2025-02-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0008_vendorcustomers_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvoice',
            name='coupon_points_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
