# Generated by Django 5.1.4 on 2026-02-10 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0009_vendorinvoice_coupon_points_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercoupon',
            name='coupon_points_hold',
        ),
        migrations.RemoveField(
            model_name='vendorcustomers',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='vendorcustomers',
            name='membership_type',
        ),
        migrations.AddField(
            model_name='salonbranch',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='swalookuserprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='swalookuserprofile',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='swalookuserprofile',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='swalookuserprofile',
            name='review',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='vendorappointment',
            name='d_o_a',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vendorappointment',
            name='d_o_b',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vendorcustomers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorcustomers',
            name='memberships',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorexpense',
            name='amount_paid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorexpense',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorexpense',
            name='due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorexpense',
            name='due_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vendorinventoryproduct',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorinventoryproduct',
            name='expiry_date',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorinventoryproduct',
            name='reorder_threshold',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='combo_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='pdf_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpdf',
            name='pdf_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorstaff',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorstaff',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorstaffattendance',
            name='image',
            field=models.ImageField(blank=True, default='default_images/default.jpg', null=True, upload_to='images/self'),
        ),
        migrations.AddField(
            model_name='vendorstaffattendance',
            name='image_1',
            field=models.ImageField(blank=True, default='default_images/default.jpg', null=True, upload_to='images/self-out'),
        ),
        migrations.AddField(
            model_name='vendorstaffattendance',
            name='in_time',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendorstaffattendance',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorstaffattendance',
            name='long',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorstaffattendance',
            name='out_lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorstaffattendance',
            name='out_long',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorstaffattendance',
            name='out_time',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='salonbranch',
            name='admin_password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='salonbranch',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='salonbranch',
            name='vendor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorappointment',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendorappointment',
            name='services',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='vendorcustomers',
            name='coupon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcustomers',
            name='loyality_profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorexpense',
            name='expense_account',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorexpense',
            name='expense_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorexpense',
            name='inventory_item',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorexpense',
            name='invoice_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='combo_services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('services', models.JSONField(blank=True, default=list)),
                ('combo_name', models.CharField(blank=True, max_length=200, null=True)),
                ('combo_price', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch')),
            ],
        ),
        migrations.CreateModel(
            name='IG_FB_shared_picture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='clp')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='clp')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTargetSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('membership_coupon_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overall_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('staff_targets', models.TextField(blank=True, null=True)),
                ('created_at', models.CharField(blank=True, max_length=200, null=True)),
                ('month', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch')),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAdvanceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateField()),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.vendorstaff')),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch')),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAttendanceTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('in_time', models.CharField(max_length=200)),
                ('out_time', models.CharField(max_length=200)),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch')),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_ExpensePurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_address', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_mobile_no', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_email', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateField()),
                ('completed_date', models.DateField()),
                ('invoice_id', models.CharField(blank=True, max_length=200, null=True)),
                ('products', models.JSONField(blank=True, default=list)),
                ('payment_term', models.CharField(blank=True, max_length=200, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('image_1', models.FileField(blank=True, null=True, upload_to='purchase')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.vendor_expensepurchase')),
            ],
        ),
        migrations.CreateModel(
            name='VendorEnquery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_for', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch')),
            ],
        ),
        migrations.CreateModel(
            name='VendorExpenseMainCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_expense_category', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch')),
            ],
        ),
        migrations.AddField(
            model_name='vendorexpensecategory',
            name='vendor_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.vendorexpensemaincategory'),
        ),
        migrations.CreateModel(
            name='VendorProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_category', models.CharField(db_index=True, max_length=300)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch')),
            ],
            options={
                'verbose_name': 'Vendor Product Category',
                'ordering': ['product_category'],
            },
        ),
        migrations.CreateModel(
            name='Utilization_Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff', models.CharField(max_length=255)),
                ('product_quantity', models.IntegerField()),
                ('created_at', models.DateField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.vendorinventoryproduct')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.vendorproductcategory')),
            ],
        ),
        migrations.AddField(
            model_name='vendorinventoryproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.vendorproductcategory'),
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_quantity', models.IntegerField()),
                ('adjustment_type', models.CharField(choices=[('Damaged', 'Damaged'), ('Expired', 'Expired'), ('Lost', 'Lost'), ('Correction', 'Correction'), ('Other', 'Other')], default='Other', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='_api_.vendorinventoryproduct')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.salonbranch')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'vendor_branch', 'date'], name='Dapi__inven_user_id_21f4eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductConsumptionTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accumulated_usage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_type', models.CharField(default='ml', max_length=20)),
                ('total_units_deducted', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_trackers', to='_api_.vendorinventoryproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_api_.salonbranch')),
            ],
            options={
                'indexes': [models.Index(fields=['vendor_branch', 'product'], name='Dapi__produ_vendor__c3c659_idx')],
                'unique_together': {('vendor_branch', 'product', 'unit_type')},
            },
        ),
        migrations.CreateModel(
            name='ServiceConsumptionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hair_length', models.CharField(default='medium', max_length=10)),
                ('service_quantity', models.IntegerField(default=1)),
                ('usage_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_type', models.CharField(max_length=20)),
                ('units_deducted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_logs', to='_api_.vendorinvoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.vendorinventoryproduct')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='_api_.vendorservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_api_.salonbranch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor_branch', 'created_at'], name='Dapi__servi_vendor__52e3ce_idx'), models.Index(fields=['invoice'], name='Dapi__servi_invoice_fe566e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceProductUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hair_length', models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long'), ('all', 'All Lengths')], default='all', max_length=10)),
                ('usage_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('ml', 'Milliliters (ml)'), ('gm', 'Grams (gm)'), ('unit', 'Full Unit')], default='percentage', max_length=20)),
                ('product_total_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_usages', to='_api_.vendorinventoryproduct')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_usages', to='_api_.vendorservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_api_.salonbranch')),
            ],
            options={
                'indexes': [models.Index(fields=['vendor_branch', 'service'], name='Dapi__servi_vendor__ce911e_idx'), models.Index(fields=['vendor_branch', 'product'], name='Dapi__servi_vendor__9efe3c_idx')],
                'unique_together': {('vendor_branch', 'service', 'product', 'hair_length')},
            },
        ),
        migrations.AddIndex(
            model_name='vendorexpensemaincategory',
            index=models.Index(fields=['user', 'vendor_branch', 'vendor_expense_category'], name='Dapi__vendo_user_id_488c03_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorproductcategory',
            index=models.Index(fields=['user', 'vendor_branch', 'product_category'], name='Dapi__vendo_user_id_62e6d6_idx'),
        ),
    ]
