# Generated by Django 5.1.4 on 2026-02-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0010_remove_customercoupon_coupon_points_hold_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='serviceproductusage',
            new_name='api_service_vendor__4c0c43_idx',
            old_name='Dapi__servi_vendor__ce911e_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceproductusage',
            new_name='api_service_vendor__53d131_idx',
            old_name='Dapi__servi_vendor__9efe3c_idx',
        ),
        migrations.AlterModelTable(
            name='serviceproductusage',
            table='api_serviceproductusage',
        ),
    ]
