# Generated by Django 5.1.4 on 2026-02-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0011_rename_dapi__servi_vendor__ce911e_idx_api_service_vendor__4c0c43_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productconsumptiontracker',
            new_name='api_product_vendor__d94fdb_idx',
            old_name='Dapi__produ_vendor__c3c659_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceconsumptionlog',
            new_name='api_service_vendor__67d106_idx',
            old_name='Dapi__servi_vendor__52e3ce_idx',
        ),
        migrations.RenameIndex(
            model_name='serviceconsumptionlog',
            new_name='api_service_invoice_cc8c9a_idx',
            old_name='Dapi__servi_invoice_fe566e_idx',
        ),
        migrations.AlterModelTable(
            name='productconsumptiontracker',
            table='api_productconsumptiontracker',
        ),
        migrations.AlterModelTable(
            name='serviceconsumptionlog',
            table='api_serviceconsumptionlog',
        ),
    ]
