# Generated by Django 5.1.4 on 2026-02-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0012_rename_dapi__produ_vendor__c3c659_idx_api_product_vendor__d94fdb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinventoryproduct',
            name='pack_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendorinventoryproduct',
            name='stocks_in_hand',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
