# Generated by Django 5.1.4 on 2026-03-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0013_add_pack_size_and_decimal_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilization_inventory',
            name='product_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
