# Generated by Django 5.1.4 on 2026-03-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0014_alter_utilization_inventory_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinvoice',
            name='total_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
